/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedApplyRouteImport } from './routes/_authenticated/apply'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInterviewRouteImport } from './routes/_authenticated/interview'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'
import { Route as AuthenticatedAdminPanelRouteImport } from './routes/_authenticated/_admin/panel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplyRoute = AuthenticatedApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewRoute = AuthenticatedInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPanelRoute = AuthenticatedAdminPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/apply': typeof AuthenticatedApplyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/panel': typeof AuthenticatedAdminPanelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/apply': typeof AuthenticatedApplyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/panel': typeof AuthenticatedAdminPanelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/apply': typeof AuthenticatedApplyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/interview': typeof AuthenticatedInterviewRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRoute
  '/_authenticated/_admin/panel': typeof AuthenticatedAdminPanelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/apply' | '/dashboard' | '/interview' | '/admin' | '/panel'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/auth' | '/apply' | '/dashboard' | '/interview' | '/admin' | '/panel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_admin'
    | '/_authenticated/apply'
    | '/_authenticated/dashboard'
    | '/_authenticated/interview'
    | '/_authenticated/_admin/admin'
    | '/_authenticated/_admin/panel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apply': {
      id: '/_authenticated/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof AuthenticatedApplyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview': {
      id: '/_authenticated/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof AuthenticatedInterviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/panel': {
      id: '/_authenticated/_admin/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedAdminPanelRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRoute
  AuthenticatedAdminPanelRoute: typeof AuthenticatedAdminPanelRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRoute,
    AuthenticatedAdminPanelRoute: AuthenticatedAdminPanelRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedApplyRoute: typeof AuthenticatedApplyRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInterviewRoute: typeof AuthenticatedInterviewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedApplyRoute: AuthenticatedApplyRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInterviewRoute: AuthenticatedInterviewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
